<?php
declare(strict_types=1);

require_once __DIR__ . '/../includes/auth.php';
$user = require_admin();
require_once __DIR__ . '/../includes/backup-helpers.php';   
$pageTitle = 'Backup & Restore';
require_once __DIR__ . '/../includes/header.php';

// Table row counts for preview
$tableSizes = [];
foreach (backup_tables() as $t) {
    try {
        $tableSizes[$t] = (int)$pdo->query("SELECT COUNT(*) FROM `$t`")->fetchColumn();
    } catch (Throwable $e) {
        $tableSizes[$t] = null;
    }
}

$totalRows = array_sum(array_filter($tableSizes, fn($n) => $n !== null));
?>
<style>
.dash-grid { display:grid; grid-template-columns:1fr 1fr; gap:18px; }
.field { display:flex; flex-direction:column; gap:6px; font-size:.85rem; font-weight:600; color:var(--text-2); margin-bottom:14px; }
.field input[type="file"] {
    padding:11px 12px; border:1.5px solid var(--border); border-radius:8px;
    background:var(--surface); color:var(--text); font:inherit; font-size:.9rem;
}
@media (max-width:900px) { .dash-grid { grid-template-columns:1fr; } }
</style>
<div class="page-head">
    <div>
        <h1>Backup &amp; Restore</h1>
        <p>Download a full SQL dump, or restore from a previous one.</p>
    </div>
    <div class="page-head-actions">
        <a href="/scms/admin/import-members.php" class="btn btn-outline">Import members (CSV)</a>
        <a href="/scms/admin/backup-export.php" class="btn btn-primary">⬇ Download backup</a>
    </div>
</div>

<?php if ($msg = flash('success')): ?>
    <div class="alert alert-success"><?= e($msg) ?></div>
<?php endif; ?>
<?php if ($msg = flash('error')): ?>
    <div class="alert alert-error"><?= e($msg) ?></div>
<?php endif; ?>

<div class="dash-grid">

    <!-- Backup card -->
    <div class="card animate-fade-up">
        <h3 class="card-title" style="margin-bottom:12px;">Create a backup</h3>
        <p class="muted" style="font-size:.9rem;margin-bottom:18px;">
            Generates a complete SQL file you can save anywhere. Contains all your data
            for <?= number_format($totalRows) ?> rows across <?= count(array_filter($tableSizes, fn($n) => $n !== null)) ?> data tables.
        </p>

        <div class="table-wrap" style="margin-bottom:18px;">
            <table class="table" style="font-size:.82rem;">
                <thead><tr><th>Table</th><th style="text-align:right;">Rows</th></tr></thead>
                <tbody>
                <?php foreach ($tableSizes as $t => $n): ?>
                    <tr>
                        <td><code><?= e($t) ?></code></td>
                        <td style="text-align:right;">
                            <?= $n === null ? '<span class="muted">missing</span>' : number_format($n) ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>

        <a href="/scms/admin/backup-export.php" class="btn btn-primary btn-block">
            ⬇ Download .sql file
        </a>
        <p class="muted" style="font-size:.78rem;margin-top:10px;">
            File name will include the current date. Keep it somewhere safe.
        </p>
    </div>

    <!-- Restore card -->
    <div class="card animate-fade-up delay-1" style="border:1px solid rgba(239,68,68,.35);">
        <h3 class="card-title" style="margin-bottom:12px;color:var(--danger);">⚠️ Restore from backup</h3>
        <p class="muted" style="font-size:.9rem;margin-bottom:18px;">
            This will <strong>overwrite</strong> your current database. All members, savings,
            loans, and transactions will be replaced with the contents of the uploaded file.
            <strong>You cannot undo this.</strong>
        </p>

        <div class="alert alert-error" style="font-size:.85rem;">
            <strong>Before you restore:</strong>
            <ul style="margin-top:6px;padding-left:18px;">
                <li>Download a fresh backup (left) so you can roll back if needed.</li>
                <li>Make sure no one else is using the system.</li>
                <li>Only upload files generated by this same system.</li>
            </ul>
        </div>

        <form method="post" action="backup-import.php" enctype="multipart/form-data"
              onsubmit="return confirm('This will OVERWRITE your entire database. Are you absolutely sure?');">
            <input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>">

            <label class="field">
                <span>SQL backup file</span>
                <input type="file" name="sqlfile" accept=".sql,.txt" required>
                <small class="muted" style="font-size:.75rem;">Max 32MB. Use the .sql file downloaded from this page.</small>
            </label>

            <div class="field">
                <label style="display:flex;align-items:flex-start;gap:8px;font-size:.85rem;">
                    <input type="checkbox" name="confirm" value="1" required style="margin-top:3px;">
                    <span>I understand this will <strong>replace all current data</strong> and cannot be undone.</span>
                </label>
            </div>

            <button type="submit" class="btn btn-danger btn-block" style="margin-top:14px;">
                Restore from file
            </button>
        </form>
    </div>
</div>



<?php require_once __DIR__ . '/../includes/footer.php'; ?>